### ISSUE TITLE
BIZ- Campaign Details Video reel. Replace them. Sorry

### ISSUE THREAD

**Issue by winwisely01** [winwisely99/main#106]
Page:

Campaign Details

Screen:

![Screenshot 2019-12-30 at 17 40 49](https://user-images.githubusercontent.com/56028033/71591160-8ef17b80-2b2b-11ea-9d40-4c0ed126e51e.png)

Problem:

The Fake video REEL is wrong - images are just not right for Biz

---

Tech note:
Its an Animated gif at the moment. Dont do it this way.

The gsheet for them is here:
https://docs.google.com/spreadsheets/d/1T8rAqeU2J_gEvryhRIqWVtmh6zxwE2sRXX2Iqf__GOg/edit#gid=0&range=R:R

The gdrive folder is here:
https://drive.google.com/drive/folders/18R8DVnGtWB3Vv29r3iY_GDRepJl12DtH
- 1080 x 768. PNG, No compression. 

Where to source the images ??
@winwisely01 / @winwisely02 
Suggest you guys use these or other sources.
https://unsplash.com/s/photos/striking

Tech note:

@thevzurd 

- Just make it still images and hook a timer to run through them.
- Overlay a Video Playing. Use SVG. Get one from the web. google for it.

Now its 100% data driven !!

**Comment by winwisely33** [comment]
The new images are uploaded in the drive.
