### ISSUE TITLE
Bug: @thevizurd Sign-in  button does not work

### ISSUE THREAD

**Issue by winwisely01** [winwisely99/main#111]
@thevzurd 
url: same as always
SS: faulty signin home page:

<img width="1440" alt="SS-faulty signin home page" src="https://user-images.githubusercontent.com/57300490/71569336-fcea6400-2a93-11ea-894b-8f51b01233ad.png">

When already joined user comes back to the site and clicks "sign-in" he is taken to this page (see SS attached) which makes no sense, and whose link, "my campaigns" does not work

**Comment by winwisely99** [comment]
NA
