### ISSUE TITLE
gen

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#21]
Make sure the make file has a gen target and does anything needed at Compile time

- protobuf code gen

- icon generation

---

Later we can integrate the i18n and test data, but this will probably be in a different Make target

**Comment by thevzurd** [comment]
Have pushed changes. Can you please test if the make files work with non-windows OS as well ?

**Comment by thevzurd** [comment]
So we need golang gen for protobuf to gen the server side. Now I know we created the server to mock, but if we are going to proceed with building the serverside on golang, then we will have to add this step in our bootstrap. For now, I have added it in the server side makefile.
