### ISSUE TITLE
Mock Data ( code gen ) - design notes

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#27]
Mock data

- enrollment uses strong typing at the moment
- others is using week typing in common network package
- so opportunity is to integrate the google sheets concept ( like the localise plugin does)

a. Design time: suck the data down from google sheest
b. Design time: parse to disk as as CSV.
c. Add to Network.dart the ability to suck it up at runtime from the CSV.
d. LATER we can at design time, parse the CSV and gen strongly typed IF we want to.
e. Later we will do exactly the same thing server side to pump data form that layer.
f. SO build the design time tools in golang.
- joe can flesh out that bit into a common tool.

**Comment by thevzurd** [comment]
Made changes to load image and data from assets during build.
