### ISSUE TITLE
Add a drawer

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#3]
This ones: https://github.com/go-flutter-desktop/examples/tree/master/stocks

Its a debugger drawer and exactly what we need because its has
- full debug gui
- i18n lang
- about which then lists all open source project used. Important for funding.
- fonts
   - you need to move roboto into this repo because no all desktops have the font. Its a form of embedding

**Comment by thevzurd** [comment]
@winwisely99 do you mean these debug settings ?

![image](https://user-images.githubusercontent.com/31169070/68348920-66b84400-00c9-11ea-83d4-f14d36824f1e.png)

And these for the licences ?

![image](https://user-images.githubusercontent.com/31169070/68348961-8a7b8a00-00c9-11ea-9379-fe5dd4d8a7a6.png)

**Comment by thevzurd** [comment]
- [x] full debug gui

- [ ] about which then lists all open source project used. Important for funding.
fonts


- [ ] i18n lang

- [x] you need to move roboto into this repo because no all desktops have the font. Its a form of embedding

**Comment by winwisely99** [comment]
everything is awesome :)

nice work

**Comment by winwisely99** [comment]
The i18n aspect is to allwo changing the lang in the GUI.
this is so that its easy to test.
we also need to be able to feed it on from a variable at start up so that when we test and run the screenshottter later we can make screen shots in the users lang.
