### ISSUE TITLE
Master-detail View

### ISSUE THREAD

**Issue by thevzurd** [winwisely99/main#37]

**Comment by winwisely99** [comment]
a classic solution to the issue of having to run on tiny screens and big screens is to use the master detail pattern.

Master is the List view. Detail is the form view.

CHat for example has a list of all your chats ( master view)
Chat has a form that shows a single chat ( detail ).

On mobile the master is a side bar drawer Or just a view. 
The detail a single chat.

On Desktop the master is always on the left, and the detail always on the right.
