### ISSUE TITLE
Not Ready Metrics collection: Screen controls locked

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#38]
Darwin.
The slider and the many checkbox are locked.

![Screenshot 2019-11-18 at 11 12 56](https://user-images.githubusercontent.com/56028033/69044746-c251ce00-09f5-11ea-9499-697197e69d1a.png)

**Comment by winwisely99** [comment]
Also add a page name.
We need them so that error reporting is consistent.
"Not Ready metrics" will do your now..

**Comment by thevzurd** [comment]
actually the whole enrollment / campaign modules needs re-writing. It doesnt have caching enabled as well. I will implement these changes along with the others

**Comment by winwisely99** [comment]
ok

On Mon, 18 Nov 2019 at 17:54, thevzurd <notifications@github.com> wrote:
>
> actually the whole enrollment / campaign modules needs re-writing. It doesnt have caching enabled as well. I will implement these changes along with the others
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Telegram ( as gedw99 )

**Comment by winwisely99** [comment]
@thevzurd 
JUST turn on the controls for now for the demo. We dont need anything else behind it for the demo.
ALSO give the screen a name "User needs"
ALSO change the strap line to: "What do you need to join " ?
