### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#4]
add logo.

everyone uses: https://pub.dev/packages/flutter_launcher_icons
It does the conversion for you for desktop and mobile.

Example: 
https://github.com/HPI-de/hpi_flutter/blob/dev/pubspec.yaml#L52

https://github.com/HPI-de/hpi_flutter/blob/dev/pubspec.yaml#L72
- important to do it this way so it works on all androids

@winwisely33 

I need logos to be same ones as here in terms of shape and quantity.

assets: https://github.com/HPI-de/hpi_flutter/tree/dev/assets/logo
- not how they have many versions to cope with different OS's

**Comment by winwisely33** [comment]
![foreground](https://user-images.githubusercontent.com/56328781/68239201-2e810a80-ffd0-11e9-810a-01c5da0ba3ec.png)
![icon](https://user-images.githubusercontent.com/56328781/68239205-2e810a80-ffd0-11e9-9850-002db2d178c1.png)
![logo_captionWhite](https://user-images.githubusercontent.com/56328781/68239206-2e810a80-ffd0-11e9-9acd-574094595b7e.png)
![logo_text](https://user-images.githubusercontent.com/56328781/68239207-2f19a100-ffd0-11e9-9b78-e2fa46d04ab9.png)
![logo](https://user-images.githubusercontent.com/56328781/68239208-2f19a100-ffd0-11e9-9383-f0ffdbc0ac81.png)

**Comment by thevzurd** [comment]
![image](https://user-images.githubusercontent.com/31169070/68268517-85b0ca80-0024-11ea-9e14-d4c1ad890334.png)

@winwisely33 , can you please put the images as a zip file or something similar to how it is in the screenshot. This is the standard structure.

**Comment by winwisely33** [comment]
So each one just has to be in its own directory? Do the labels matter?  I
followed the ones here
https://github.com/HPI-de/hpi_flutter/tree/dev/assets/logo which are
different styled versions, not the same logo with different res versions.

**Comment by winwisely33** [comment]
So basically I'm asking of you need the same main logo icon to be in
different specs?  Or use the ones I already made.

**Comment by thevzurd** [comment]
It's a standard that's all. I know that android looks up for these names.
And iOS is also very similar. So it's good to have in the standard format

**Comment by winwisely33** [comment]
Ok I'll have to look up the specs

**Comment by winwisely33** [comment]
[Icons.zip](https://github.com/winwisely99/main/files/3812775/Icons.zip)
@thevzurd I wasn't sure what to put in the values folder so I left it empty.

**Comment by thevzurd** [comment]
yes. thanks @winwisely33

**Comment by thevzurd** [comment]
Added the code gen and also to the make file
