### ISSUE TITLE
GRPC: Extend for our other Modules

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#43]
DONT break the Flutter code and the existing golang chat code !!!

- everything below is not in that area so you should be ok.

@thevzurd can help you if you need help on the flutter code later

Also here is what everyone is working on:
https://github.com/winwisely99/main/projects/1

0. Setup

- Make a bootstrapper for linux. Use mac as the reference:
https://github.com/winwisely99/bootstrap/tree/master/mac

1. Chat currently works and is in memory which is fine.

- Get this running on Cloudrun. See Network repo for examples !!
  - https://github.com/winwisely99/network/tree/master/hosting/google-cloudrun/avatar
- Use your own gmail account with gcloud to deploy.

2. Enrollment

- Needs GRPC bring up.
- Make the Proto
- This is NOT real time streaming so but RPC so easier.

3. Signin

- GRPC is good enough. We dont need complex jwt as our security is pretty customised anyway
- in memory for now.
- make a Proto
- Cloudrun

4. News

- Its Streaming.
- Use Google Storage because its just JSON and blobs.
- has images too, but those would be out of the stream

Debugging
------------

We need an approach for debugging the golang GRPC stuff
Right now GRPC gateway and other nice tools look good and @winwisely99 will sort that bit out

**Comment by thevzurd** [comment]
@idirall22 I have added proto files to match the data structure on the client side. Please have a look.

**Comment by idirall22** [comment]
OK i 'll check the files
