### ISSUE TITLE
Markdown Rendering for News

### ISSUE THREAD

**Issue by thevzurd** [winwisely99/main#44]
Replace News with markdown format. This wil make it easy for us to build filters on the backend and also for the front end to have basic formatting like heading being bold etc.

@winwisely02 Replace the news data with markup

**Comment by winwisely02** [comment]
@thevzurd I thought I did that, but maybe not... When i copy the text into vs code, what do I need to do then before copying it back into the g-sheet?

**Comment by thevzurd** [comment]
@winwisely02 Actually, this is more of an action point for me at the moment, to make changes to support markdown rendering in the future. Markdown Rendering makes features like Titles , font weight etc possible in normal text.
For eg:
This is normal text I write as Title
## This is normal text I write as Title with Markdown 
see the difference ?

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

This list has various options we can use. If you want to use it with the News data you are preparing for load in the gsheet, you always can. In the future, we expect to receive News Feed from sources in this format.
