### ISSUE TITLE
News data needs to be more verbose

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#48]
Need them to be like 200 to 500 lines for each

Just pinch some from the web, copy and paste into VSCODE and formt as markdown and copy into gheet

e.g

https://www.theguardian.com/environment/2019/nov/18/climate-crisis-striking-a-blow-for-windfarms-new-research-suggests

**Comment by winwisely99** [comment]
@thevzurd SO you have decent amount on the page so it does not look dicky.

**Comment by winwisely99** [comment]
@thevzurd If you have ANY other issues with the data raise an issue and assign @winwisely02

**Comment by winwisely02** [comment]
@thevzurd the news text has been updated
