### ISSUE TITLE
convert to the protobuf with hive architecture

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#5]
This is critical to the long term architecture because we need protobufs to have version independence so we dont break users.

Also on the Server we use grpc and protobufs for everything.

code to do ti:
https://github.com/JonasWanke/immutable_proto

example:
https://github.com/HPI-de/hpi_flutter/blob/dev/pubspec.yaml
- they use koitln for server but we use golang
- This does NOT use HIVE. I think they did not have time to hook up the protobufs into the HIVE cache.

So its works like this in this order:
- server: declare your grpc / protobufs
- Server: gen your golang
- flutter: gen your mutable classes
- flutter: gen your immutable classes

---

The OTHER approach is to use Hive cache system, but its does not currently support Protobufs.
Ideally an architecture that uses Protobufs with HIVE is optimal and in fact mandaory when you build production systems.
- Protobufs prevents different versions of clients breaking and it about 10 times faster than json and so higher perf on the devices.
- Hive is a fantastic cross platform way to do caching.
 - hive is designed to work with Protobufs because it also has numbered fields.

Example Project:
https://github.com/schul-cloud/schulcloud-flutter/blob/master/pubspec.yaml
- they have NOT converted to the hive_cache approach yet.

The HIVE cache stuff is there:
https://github.com/marcelgarus/hive_cache
- The cache that wraps hive

https://github.com/marcelgarus/cached_listview/blob/master/example/pubspec.yaml
- this is for list views that automagically use the hive cache and do pagiantion.

https://github.com/marcelgarus/data_classes
- the generator. NOT using protobufs.Miht not need to actually as its just a binary array

----

The other approach is to NOT use protobuf.

This makes thing very simple but lower perf.

So it occured to me that it will be easy to check the JSON coming in and map the data into HIVE

And if a field is not there in hive throw it away.

Protobufs schema evolution on the cheap and easy

thats the concept... 

Easy to try it out too:
You can write a little bit of code to Test the concept without any server. Just have two hive classes that are identical but with one not having a field. Then push the JSON into each through your magic mapper.

**Comment by winwisely99** [comment]
@thevzurd FYI

**Comment by thevzurd** [comment]
Caching is now working as expected with protobuf/hive layer.
