### ISSUE TITLE
Web Demo: Data missing Enrolment Campaigns page

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#57]
No Data on Campaign Name page. There should be data.

**Comment by winwisely99** [comment]
The part of the app that does not show the data is when you select the details of a campaign in the Enrolment process.

This has the data:
![Screenshot 2019-12-05 at 11 11 44](https://user-images.githubusercontent.com/56028033/70225817-0eb84000-1750-11ea-8451-2473e9c530c2.png)

This does not have the data:
![Screenshot 2019-12-05 at 11 12 24](https://user-images.githubusercontent.com/56028033/70225860-21cb1000-1750-11ea-877a-b9edb990d9f0.png)


Can this please be fixed ?

**Comment by thevzurd** [comment]
yes will do. I added the data in the first page and did not know what the second page is even about.

This is what I was mentioning in the feedback. How can I even guessed that the same data needs to be in both places or that it is just redundant ? I will fix it.

**Comment by thevzurd** [comment]
@winwisely99 , there is another screen that says this as well. Are they all the same ? They are showing campaign details. Shall I consolidate everything to one master detail ?
Master - campaign and detail with all this data and on the bottom the ready not ready switch ?

![image](https://user-images.githubusercontent.com/31169070/70240066-909d6e80-173a-11ea-8280-2a3a287c039b.png)

**Comment by thevzurd** [comment]
I have pushed some changes. Yet to fix the roles  age.

**Comment by winwisely99** [comment]
Ok i played the demo.

You got rid of the two screens into 1. Its good. Leave it this way.
Master detail responsive design is great.

---

ONE little bug.

In desktop mode its fine

![Screenshot 2019-12-06 at 08 55 24](https://user-images.githubusercontent.com/56028033/70306064-28b45a00-1806-11ea-92f4-f89a61e94bf5.png)

In mobile mode we lost our back button :)

![Screenshot 2019-12-06 at 08 55 46](https://user-images.githubusercontent.com/56028033/70306079-35d14900-1806-11ea-9c40-2e4b38d44ee9.png)
