### ISSUE TITLE
BIZ: Web Demo - Not showing side bar on IOS

### ISSUE THREAD

**Issue by winwisely02** [winwisely99/main#67]
## Describe the bug

Description: On the home page, where the news feed is, I cannot see the side bar icons (ie home, chat, etc). I only see these icons when I go to the settings page. 

Where: On the home page.

## Steps to Reproduce the bug

1. Choose Sign In to get to the Home/News page (ICONS MISSING)
2. Go to Settings (ICONS APPEAR)

## Screenshots Or Video

Description 1: This is the home page, where you don't have the option to choose from the side bar.
![home-withouticons](https://user-images.githubusercontent.com/56081026/70357188-e7d73800-183b-11ea-8cfa-f9027668d05e.png)
---
Description 2: This is the settings page, where the side bar appears.
![settings-withicons](https://user-images.githubusercontent.com/56081026/70357292-28cf4c80-183c-11ea-9ce5-16459bd9583b.png)
---
Description 3: This is what it looks like on the desktop version.
![Screen Shot 2019-12-06 at 3 26 14 pm](https://user-images.githubusercontent.com/56081026/70357584-e22e2200-183c-11ea-91a9-07aec1d6319d.png)

## Environment
- Operating System:  IOS
- Device:  iPhone 7
- App version: Web Demo
- Module:

**Comment by winwisely99** [comment]
1. There is now Home page. It just shows the News for now. 

- We need to decide what the home page should show. I think it needs to be a dashboard to show the status of the user in relation to the campaigns they are in.

2. Also the Home page will be different for a Campaign manager.

- The campaign manage can have many volunteers.
- What is the Campaign manager interested in knows on their Dashboard.

All the other stuff like News and Chat are messaging tools.

**Comment by winwisely99** [comment]
@winwisely02 This is all getting fixed as part of an architectural change.

We are changing to have a bottom nav for Web, Mobile and desktop.  After looking at all the tradeoffs this is the best solution.
Bottom nav is much more easier for users on Mobile which is the highest user base, and yet works fine on web and desktop

Side nav draw will only be used for settings, which are things a user does not use often
