### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#7]
We need to be able to run on Large screens and Small screens

Start with this:
https://github.com/aloisdeniel/flutter_device_preview
- will make testing super fast
- makes screenshots automatic
- runs on desktop so fast dev cycles.

Then we should look around for good patterns to make this easy to do such that your code stays DRY.
They have already started it here: https://github.com/aloisdeniel/flutter_device_preview/issues/10

Now because it runs on desktop you are going to hit the issue of code having dependencies on plugins that only work on mobile. 
- This is why its better to use only plugins that are supported by go-flutter
- Its also why we are vendoring al plugins in the plugin repo, and also working up desktop equivalents.

**Comment by thevzurd** [comment]
Windows Desktop
![image](https://user-images.githubusercontent.com/31169070/68392710-5b503180-0138-11ea-9611-68b2d5135cf1.png)

![image](https://user-images.githubusercontent.com/31169070/68392779-8f2b5700-0138-11ea-849f-42488d005851.png)

![image](https://user-images.githubusercontent.com/31169070/68392827-abc78f00-0138-11ea-81a0-16c596476a26.png)

![image](https://user-images.githubusercontent.com/31169070/68393003-082aae80-0139-11ea-8913-02fd248d8ddf.png)

![image](https://user-images.githubusercontent.com/31169070/68393057-209ac900-0139-11ea-8b25-c513cd446500.png)

![image](https://user-images.githubusercontent.com/31169070/68393079-2ee8e500-0139-11ea-9eda-41bf8e9c2e75.png)

![image](https://user-images.githubusercontent.com/31169070/68393097-3f995b00-0139-11ea-9f64-421e4b7d6387.png)

![image](https://user-images.githubusercontent.com/31169070/68393113-4fb13a80-0139-11ea-8363-654f0f48bed0.png)

![image](https://user-images.githubusercontent.com/31169070/68393147-69528200-0139-11ea-9bf2-c2ddb6383175.png)

![image](https://user-images.githubusercontent.com/31169070/68393163-74a5ad80-0139-11ea-8dea-87ec08266222.png)

![image](https://user-images.githubusercontent.com/31169070/68393176-7d967f00-0139-11ea-80d8-26613535f5b0.png)

![image](https://user-images.githubusercontent.com/31169070/68393194-89824100-0139-11ea-9c18-4828a3295ff7.png)
