### ISSUE TITLE
BIZ: Support Roles:  Add more roles (READY)

### ISSUE THREAD

**Issue by winwisely02** [winwisely99/main#79]
On the page called "Support Roles".

## Describe the bug

Description: 

1. Currently there are only 6 roles showing, when there should be all MANY MORE ( from the database)

The data is here: https://docs.google.com/spreadsheets/d/1BwxVXs8ip5cMvwYDyZMtlyJ91jh-BN6RFedIsk_uGYk

- DO NOT use the top 2. See Column C in the sheet ( use the mandatory boolean to filter at runtime).

2. Add "OK" Button to the bottom.

- When they click this take the user to the Sign Page.

**Comment by winwisely99** [comment]
1. where are the other 21  then ?

2. Where are they meant to progress to ?
