### ISSUE TITLE
BIZ: Privacy/security statement on the signup page 

### ISSUE THREAD

**Issue by winwisely02** [winwisely99/main#82]
## Description

There should be a link to the privacy and security statement (in the form of a pop up) underneath the 'Sign up button'

![Screen Shot 2019-12-20 at 3 07 33 pm](https://user-images.githubusercontent.com/56081026/71376567-83c8a980-2587-11ea-83b9-a04ddc23781a.png)

It should say this: 
"Currently in development, to assure a highly secure system based on End to End encryption principles. On the users devices all user data is encrypted at rest against the users public key. On our servers, all data in transit or at rest is encrypted against the users public key. User aggregation is not done."

**Comment by winwisely99** [comment]
Need more precise info.....

**Comment by winwisely02** [comment]
1. Before the user clicks next after putting in their location details, there should be a small message that says "All of your information is stored securely. You can see our full privacy policy on our website [hyperlink to website].

2. Here is the link to the privacy policy https://getcouragenow.org/privacy/ . Would be cool to be able to access it from the app as well, maybe in the setting section because it is accessable by users before they have finished the enrolment process. 

@winwisely99 What else do you need?

**Comment by winwisely99** [comment]
Tech note:

We dont want to open web links when not need. So better to embed it as Markdown.
The hugo web site is also Markdown. So just copy it from there.

Use the Flutter markdown plugin that we will use for News.

**Comment by thevzurd** [comment]
@winwisely02 @winwisely99 At the moment , I am putting the policy from Hugo. Can you please confirm the right one ?

**Comment by winwisely99** [comment]
done

**Comment by winwisely02** [comment]
@thevzurd can you please replace the hugo text with the text I added to the issue underneath the screenshot

**Comment by thevzurd** [comment]
Done

**Comment by winwisely02** [comment]
hey @thevzurd - did you already change it to the text I gave above? They want to change it back to the hugo version. If you already changed it can you please change it back? Sorry..
