### ISSUE TITLE
BIZ: Web demo - Video of Powerpoint demo

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/main#90]
Biz wants the PPT Video to be put into the demo

1. Whats the URL ?
2. Where inthe demo to run it ?
  - Need a single page in the flow.

Tech Notes:

1. We dont have a Server that can stream videos. So Biz will have to upload to YouTube
2. The Video Player only works in Web and Mobile. Desktop does not work.

STATUS: ONHOLD
Should wait and do it properly because we know we need cross platform video playing and we are working on it.

**Comment by winwisely02** [comment]
What video? @winwisely99

**Comment by thevzurd** [comment]
descoped on request.
