### ISSUE TITLE
BIZ: Web demo - Remove the logo 

### ISSUE THREAD

**Issue by winwisely02** [winwisely99/main#92]
Remove the WinWisely logo and 'Winwisely99' from the header, the logo from the front page, and from the sign in page. Replace with place holder that says "Your logo here". 

![Screen Shot 2019-12-06 at 3 26 14 pm](https://user-images.githubusercontent.com/56081026/71022495-3602fb80-20c6-11ea-8e95-6fc7f3bbe52c.png)

![Screen Shot 2019-12-19 at 12 46 20 pm](https://user-images.githubusercontent.com/56081026/71200555-de979380-225d-11ea-89a8-e6be93359b68.png)

![Screen Shot 2019-12-19 at 12 49 07 pm](https://user-images.githubusercontent.com/56081026/71200631-05ee6080-225e-11ea-8a67-0fb39f13a3f2.png)

**Comment by thevzurd** [comment]
@winwisely02 Waiting for the placeholder graphics
