### ISSUE TITLE
BIZ: Web demo - update home page

### ISSUE THREAD

**Issue by winwisely02** [winwisely99/main#93]
See issue here - 
https://docs.google.com/document/d/1lEVT46F4Lia7orInXIzyGzzB_aKVzJsoRLW_F6FbDfI/edit?folder=1gAT5POcyQciRGXKoiVR7A8pMkokAD5Dk

**Comment by winwisely02** [comment]
hey @thevzurd this is the issue I made for the home page, can you have a look at it and see if it makes sense on your end? (:

**Comment by thevzurd** [comment]
1. Change to My Campaign
2. User actions at the end of Campaign Details
3. Show only user enrolled Campaigns
